create table if not exists users(
  id integer GENERATED BY DEFAULT AS IDENTITY(START WITH 1),
  account varchar(40) NOT NULL,
  password varchar(40) NOT NULL,
  status integer NOT NULL,
  regtime varchar(40) NOT NULL
);
INSERT INTO users VALUES (1, 'rzy', '21218cca77804d2ba1922c33e0151105', 1, '2018-01-01');  
INSERT INTO users VALUES (2, 'ruanzy', '52c69e3a57331081823331c4e69d3f2e', 1, '2018-01-02'); 

create table if not exists log_login(
  id integer GENERATED BY DEFAULT AS IDENTITY(START WITH 1),
  user varchar(40) NOT NULL,
  time integer NOT NULL,
  ip varchar(40) NOT NULL,
  succeed boolean NOT NULL,
  msg varchar(40) NOT NULL
  
); 

create table if not exists log_login(
  id integer GENERATED BY DEFAULT AS IDENTITY(START WITH 1),
  user varchar(40) NOT NULL,
  time integer NOT NULL,
  ip varchar(40) NOT NULL,
  succeed boolean NOT NULL,
  msg varchar(40) NOT NULL
);