create table if not exists users(
  id integer GENERATED BY DEFAULT AS IDENTITY(START WITH 1),
  name varchar(40) NOT NULL,
  password varchar(40) NOT NULL,
  depart integer NOT NULL,
  status integer NOT NULL,
  regtime varchar(40) NOT NULL
);
INSERT INTO users VALUES (1, 'rzy', '21218cca77804d2ba1922c33e0151105', 7, 1, '2018-01-01');  
INSERT INTO users VALUES (2, 'ruanzy', '52c69e3a57331081823331c4e69d3f2e', 7, 1, '2018-01-02'); 

create table if not exists dept(
  id integer GENERATED BY DEFAULT AS IDENTITY(START WITH 1),
  name varchar(40) NOT NULL,
  deep integer NOT NULL, 
  pid integer NOT NULL,
  isparent integer NOT NULL
);

insert into dept values(1, '总公司', 0, -1, 1);
insert into dept values(2, '上海分公司', 1, 1, 1);
insert into dept values(3, '江苏分公司', 1, 1, 1);
insert into dept values(4, '广州分公司', 1, 1, 1);
insert into dept values(5, '北京分公司', 1, 1, 1);
insert into dept values(6, '杭州分公司', 1, 1, 1);
insert into dept values(7, '研发部', 2, 3, 0);
insert into dept values(8, '测试部', 2, 3, 0);
insert into dept values(9, '系统部', 2, 3, 0);
insert into dept values(10, '运营部', 2, 3, 0);

create table if not exists userrole(
  userid varchar(40) NOT NULL,
  roleid integer NOT NULL
);

create table if not exists resources(
  id integer NOT NULL,
  name varchar(20) NOT NULL,
  namecode varchar(20) NOT NULL,
  type char(1) NOT NULL,
  method varchar(100)  NULL,
  url varchar(100)  NULL,
  pid integer NOT NULL,
  iconcls varchar(20)  NULL,
  deep integer NOT NULL,
  flag char(1) NOT NULL
);

insert into resources values(1, '仪表盘', 'DASHBOARD', 'm', '', '', -1, '', 1, '1');
insert into resources values(2, '数据源管理', 'DATASOURCE', 'm', '', '', -1, '', 1, '1');
insert into resources values(3, '图表管理', 'CHARTS', 'm', '', '', -1, '', 1, '1');
insert into resources values(4, '用户管理', 'USER', 'm', '', '', -1, '', 1, '1');
insert into resources values(5, '日志管理', 'LOG', 'm', '', '', -1, '', 1, '1');
insert into resources values(6, '用户新增', 'USERADD', 'o', '', '', 4, '', 2, '0');
insert into resources values(7, '用户删除', 'USERDEL', 'o', '', '', 4, '', 2, '0');
--insert into resources values(3, '新建用户', 'o', '', '', 1, '', '1/3', '1');
--insert into resources values(4, '删除用户', 'o', '', '', 1, '', '1/4', '1');
--insert into resources values(5, '新建角色', 'o', '', '', 2, '', '2/5', '1');

create table if not exists role(
  id integer GENERATED BY DEFAULT AS IDENTITY(START WITH 1),
  name varchar(20) NOT NULL
);
insert into role(name) values('管理员');
insert into role(name) values('操作员');

create table if not exists roleres(
  roleid integer NOT NULL,
  resid integer NOT NULL
);
insert into roleres values(1, 1);
insert into roleres values(1, 2);
insert into roleres values(1, 3);
insert into roleres values(1, 4);
insert into roleres values(1, 5);
insert into roleres values(1, 6);
insert into roleres values(1, 7);
insert into roleres values(2, 1);
insert into roleres values(2, 2);
insert into roleres values(2, 3);


create table if not exists deptres(
  deptid integer NOT NULL,
  resid integer NOT NULL
);

insert into deptres values(7, 1);
insert into deptres values(7, 2);
insert into deptres values(7, 3);
insert into deptres values(7, 4);
insert into deptres values(7, 5);
insert into deptres values(7, 6);

create table if not exists logs(
 	id integer GENERATED BY DEFAULT AS IDENTITY(START WITH 1),
	operator varchar(20) NOT NULL, 
	ip varchar(40) NOT NULL, 
	time varchar(40) NOT NULL, 
	operation varchar(20) NOT NULL, 
	memo varchar(1000) NOT NULL
);

create table if not exists log_login(
  id integer GENERATED BY DEFAULT AS IDENTITY(START WITH 1),
  user varchar(40) NOT NULL,
  time integer NOT NULL,
  ip varchar(40) NOT NULL,
  succeed boolean NOT NULL,
  msg varchar(40) NOT NULL
  
); 

create table if not exists log_login(
  id integer GENERATED BY DEFAULT AS IDENTITY(START WITH 1),
  user varchar(40) NOT NULL,
  time integer NOT NULL,
  ip varchar(40) NOT NULL,
  succeed boolean NOT NULL,
  msg varchar(40) NOT NULL
);